services:
  boostrap-bot:
    build: .
    container_name: boostrap-bot
    volumes:
      - ./config:/app/config:ro
    environment:
      - BOT_NAME=boostrap
      - RLBT_HOST=host.docker.internal
      - RLBT_PORT=23234

